version: '3.7'
name: "docker-go"
services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    volumes:
      - ./data:/data
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=${ZINC_FIRST_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_FIRST_ADMIN_PASSWORD}
    ports:
      - '4080:4080'

  client:
    build:
      context: ./email-client
      args:
        - VITE_API_URL= $VITE_API_URL
    depends_on:
      - server
    ports:
      - '80:8080'

  server:
    build: ./email-search
    depends_on:
      - zincsearch
    ports:
      - '8080:8080'

# docker compose up --build
